context:
  version: "0.1.0"

package:
  name: professor
  version: ${{ version }}

source:
  - git: https://github.com/gsmyridis/professor.git
    rev: 913af453197d388c5ce58e91ccb82d8a2cd916bc

build:
  number: 0
  script:
    - mojo precompile src/professor -o ${{ PREFIX }}/lib/mojo/professor.mojoc

requirements:
  build:
    - mojo-compiler ==1.0.0b3.dev2026070806
  host:
    - mojo-compiler ==1.0.0b3.dev2026070806
  run:
    - ${{ pin_compatible('mojo-compiler') }}

about:
  homepage: https://github.com/gsmyridis/professor
  repository: https://github.com/gsmyridis/professor
  license: MIT
  license_file: LICENSE
  summary: An instrumentation-based profiling library for Mojo.

extra:
  maintainers:
    - gsmyridis
